# General configuration for Jekyll

# Set the site title
title: calServer Manual

# Use the modern "Just the Docs" theme
theme: just-the-docs

# Set the base URL when hosted as a project page
url: "https://bastelix.github.io"
baseurl: "/calserver-docu"

# Enable search (default for the theme)
search_enabled: true

# Enable in-page navigation (anchor links for headings)
heading_anchors: true

# Color scheme can be light or dark
color_scheme: light

# Enable breadcrumbs
breadcrumbs: true

# Auxiliary links shown in the top right corner
aux_links:
  "GitHub": https://github.com/bastelix/calserver-docu
  "API": https://documenter.getpostman.com/view/11572884/2sA3JFCkDv
  "Impressum": https://bastelix.github.io/calserver-docu/impressum/
  "Kontakt": https://bastelix.github.io/calserver-docu/kontakt/
aux_links_new_tab: true

# Enable table of contents generation using jekyll-toc
plugins:
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      toc: true

# Exclude repository README from the generated site
exclude:
  - README.md
  # Hide placeholder READMEs within image directories
  - docs/assets/img/**/README.md
