# General configuration for Jekyll

# Set the site title
title: calServer Manual

# Use the modern "Just the Docs" theme
remote_theme: just-the-docs/just-the-docs

# Enable search (default for the theme)
search_enabled: true

# Color scheme can be light or dark
color_scheme: light

# Enable breadcrumbs
breadcrumbs: true

# Auxiliary links shown in the top right corner
aux_links:
  "GitHub": https://github.com/bastelix/calserver-docu
  "API": /api
  "Impressum": /impressum
  "Kontakt": /kontakt
aux_links_new_tab: true
